### ISSUE TITLE
RouteBuilder not found

### ISSUE THREAD

**Issue by waghanza** [ragokan/bunicorn#3]
Hi @ragokan,

In https://github.com/the-benchmarker/web-frameworks/pull/7753, you changed the implementation for `bunicorn`, but running the results for monday, I have
~~~javascript
Bun v1.1.29 (Linux arm64)
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'RouteBuilder' not found in module '/root/.bun/install/cache/@bunicorn/server@0.0.27@@@1/dist/index.js'.
~~~

Regards,

**Comment by ragokan** [comment]
Hello @waghanza 

Thanks, sorry for the issue, it is renamed to "Router", I will create a pull request for that.
I didn't thought that it would update to the latest version 

Have a great day!

**Comment by waghanza** [comment]
No need @ragokan, I'll update code base myself ;-) 

Results will be up tomorrow

**Comment by ragokan** [comment]
Thanks a lot, I still wanted to provide the updated usage.

```ts
import { Router, BunicornApp } from "@bunicorn/server";

const app = new BunicornApp();
const router = new Router();
app.addRoutes([
  router.get("/", (ctx) => ctx.ok()),
  router.get("/user/:id", (ctx) => ctx.raw(ctx.params.id)),
  router.post("/user", (ctx) => ctx.ok()),
]);

app.serve({
  port: 3000,
	reusePort: true
})
```

**Comment by waghanza** [comment]
Will update 🎉
